# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfdc63648119ad5414fb5b3f2054c6e5b57b89ea2c0d34428b221c98ade8c651467c980d88e4269ed0b28650b84dcc68f6ab822e885c8728400b148b3dd4ca38
  devise_secret_key: bcbd6ee7c6d68debd72ae6363d6e5d4519ba1e2f91e0527f84e2a74683b1c8ac656faa465735001a059a4f986db75a46efe2e26783d79f5d5538d8200d22cb52
test:
  secret_key_base: e8251a88d77e7c84375fba7862481f45d7e06388f2a49e12293354f0db0c5eb6f16f43183a34da418aff69deffee8c2300a66195c81cab110a809c26427bcc06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
